### ISSUE TITLE
Invalid encoding causes offlineimap3 to crash

### ISSUE THREAD

**Issue by sudipm-mukherjee** [OfflineIMAP/offlineimap3#107]
#### General informations

- system/distribution (with version): Debian bookworm/sid
- offlineimap version (`offlineimap -V`):  0.0~git20211018.e64c254+dfsg-1
- Python version: 3.9
-  Debian Bug: https://bugs.debian.org/1004938

#### Logs, error

```
Folder spam [acc: Test]:
 Syncing spam: IMAP -> Maildir
 Copy message UID 1353368115 (1/88) Folk:spam -> Local:spam
 Copy message UID 1353368116 (2/88) Folk:spam -> Local:spam
Copy message from Folk:spam:
 ERROR: Copying message 1353368115 [acc: Test]
  'ascii' codec can't encode characters in position 1541-1579: ordinal not in range(128)
Thread 'Copy message from Folk:spam' terminated with exception:
Traceback (most recent call last):
  File "/usr/share/offlineimap3/offlineimap/threadutil.py", line 146, in run
    Thread.run(self)
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/offlineimap3/offlineimap/folder/Base.py", line 815, in copymessageto
    new_uid = dstfolder.savemessage(uid, message, flags, rtime)
  File "/usr/share/offlineimap3/offlineimap/folder/Maildir.py", line 409, in savemessage
    tmpname = self.save_to_tmp_file(messagename, msg)
  File "/usr/share/offlineimap3/offlineimap/folder/Maildir.py", line 359, in save_to_tmp_file
    fd.write(msg.as_bytes(policy=output_policy))
  File "/usr/lib/python3.9/email/message.py", line 178, in as_bytes
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python3.9/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.9/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.9/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/lib/python3.9/email/generator.py", line 276, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.9/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.9/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.9/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/lib/python3.9/email/generator.py", line 362, in _handle_message
    g.flatten(msg.get_payload(0), unixfrom=False, linesep=self._NL)
  File "/usr/lib/python3.9/email/generator.py", line 116, in flatten
    self._write(msg)
  File "/usr/lib/python3.9/email/generator.py", line 181, in _write
    self._dispatch(msg)
  File "/usr/lib/python3.9/email/generator.py", line 218, in _dispatch
    meth(msg)
  File "/usr/lib/python3.9/email/generator.py", line 268, in _handle_multipart
    self.write(subparts)
  File "/usr/lib/python3.9/email/generator.py", line 410, in write
    self._fp.write(s.encode('ascii', 'surrogateescape'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1541-1579: ordinal not in range(128)
```

**Comment by sebastianschauenburg** [comment]
Have the same issue here. System: Ubuntu 21.10, offlineimap 3 version:  `0.0~git20210225.1e7ef9e+dfsg-4`
Have updated offlineimap3 to the Jammy version ( `0.0~git20211018.e64c254+dfsg-1` ), but the same issue persists.

Actual error message:

> ERROR: UID 33598 (<=?UTF-8?B?KX5+4Ke74oKr4KuxPl17e+KCpeC4v+KCpeCrsUBAQCQk4oKsJiZbW8KpwqXCpcK98J+Is/CfiLPwn4i38J+JkfCfiZHCvQ==?=@ismtpd0003p1iad1.soxqzdjapeuwoxoyf.net>) has defects preventing it from being processed!
>
>  UnicodeEncodeError: 'ascii' codec can't encode characters in position 506-507: ordinal not in range(128)

The email in question (where my username/emailaddress has been changed):
[confirmationReceipt.ID N°69206158269_modified.eml.zip](https://github.com/OfflineIMAP/offlineimap3/files/8360312/confirmationReceipt.ID.N.69206158269_modified.eml.zip)

**Comment by bohwaz** [comment]
I also have this annoying issue on 3 different emails, and no way to sync those messages.

**Comment by catap** [comment]
The cause is python bug. See: https://github.com/python/cpython/issues/76511

**Comment by catap** [comment]
https://github.com/OfflineIMAP/offlineimap3/pull/150 should fix it

**Comment by sebastianschauenburg** [comment]
Here's another example of an e-mail which causes this similar issue: [offlineimap_error_spam.txt](https://github.com/OfflineIMAP/offlineimap3/files/11649980/offlineimap_error_spam.txt)

@bohwaz thanks for debugging
@catap thanks for creating a possible patch
