### ISSUE TITLE
Support py3.12

### ISSUE THREAD

**Issue by chenrui333** [OfflineIMAP/offlineimap3#164]
I am trying to build 8.0.0 against py3.12, but ran into some build failure

```
Using pip 23.2.1 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)
Processing /private/tmp/offlineimap-20231017-80784-1fleq5o/offlineimap3-8.0.0
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  /opt/homebrew/Cellar/offlineimap/8.0.0_1/libexec/lib/python3.12/site-packages/imaplib2/imaplib2.py:2493: SyntaxWarning: invalid escape sequence '\D'
    ('store', ('1', 'FLAGS', '(\Deleted)')),
  /opt/homebrew/Cellar/offlineimap/8.0.0_1/libexec/lib/python3.12/site-packages/imaplib2/imaplib2.py:2598: SyntaxWarning: invalid escape sequence '\D'
    run('uid', ('STORE', uid[-1], 'FLAGS', '(\Deleted)'))
  /opt/homebrew/Cellar/offlineimap/8.0.0_1/libexec/lib/python3.12/site-packages/imaplib2/imaplib2.py:2612: SyntaxWarning: invalid escape sequence '\S'
    run('store', (num, '-FLAGS', '(\Seen)'), cb=False),
  /opt/homebrew/Cellar/offlineimap/8.0.0_1/libexec/lib/python3.12/site-packages/imaplib2/imaplib2.py:2615: SyntaxWarning: invalid escape sequence '\D'
    run('uid', ('STORE', num, 'FLAGS', '(\Deleted)'))
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/private/tmp/offlineimap-20231017-80784-1fleq5o/offlineimap3-8.0.0/setup.py", line 25, in <module>
      import offlineimap
    File "/private/tmp/offlineimap-20231017-80784-1fleq5o/offlineimap3-8.0.0/offlineimap/__init__.py", line 20, in <module>
      from offlineimap.init import OfflineImap
    File "/private/tmp/offlineimap-20231017-80784-1fleq5o/offlineimap3-8.0.0/offlineimap/init.py", line 35, in <module>
      from offlineimap import threadutil, accounts, folder, mbnames
    File "/private/tmp/offlineimap-20231017-80784-1fleq5o/offlineimap3-8.0.0/offlineimap/accounts.py", line 24, in <module>
      from offlineimap import mbnames, CustomConfig, OfflineImapError
    File "/private/tmp/offlineimap-20231017-80784-1fleq5o/offlineimap3-8.0.0/offlineimap/CustomConfig.py", line 20, in <module>
      from configparser import SafeConfigParser, Error
  ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/opt/homebrew/Cellar/python@3.12/3.12.0/Frameworks/Python.framework/Versions/3.12/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
  error: subprocess-exited-with-error
```

relates to https://github.com/Homebrew/homebrew-core/pull/151139

**Comment by thekix** [comment]
Hi @chenrui333 

Please, could you try to change in the file `offlineimap/CustomConfig.py` the word (Class) "SafeConfigParser" with the word (Class) "ConfigParser"? This string is three times in the file. See the diff code below.

The reason seems that SafeConfigParser was renamed to ConfigParser in Python 3.2, and the SafeConfigParser name was kept for backward compatibility until Python 3.11. So we can use ConfigParser instead of SafeConfigParser.

If you try it and it works fine, I will create a new pull-request. Also, you can create it if you want.

Best regards,
kix


```
kix:~/src/offlineimap3/offlineimap$ diff CustomConfig.py-new CustomConfig.py
20c20
< from configparser import ConfigParser, Error
---
> from configparser import SafeConfigParser, Error
24c24
< class CustomConfigParser(ConfigParser):
---
> class CustomConfigParser(SafeConfigParser):
26c26
<         ConfigParser.__init__(self)
---
>         SafeConfigParser.__init__(self)
kix:~/src/offlineimap3/offlineimap$ 

```
