### ISSUE TITLE
Gmail FETCH error after updating offlineimap

### ISSUE THREAD

**Issue by dinosv** [OfflineIMAP/offlineimap3#52]
#### General informations

- system/distribution (with version):  Debian GNU/Linux bullseye (20210217 updated)
- offlineimap version (`offlineimap -V`): offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.1+, OpenSSL 1.1.1i  8 Dec 2020
- Python version: Python 3.8.3
- server name or domain: imap.gmail.com
- CLI options: none

#### Configuration file offlineimaprc

```
[general]
accounts = GmailWork

[Account GmailWork]
localrepository = Gmaillocalmine
remoterepository = Gmailservermine
synclabels = yes
# This header is where labels go.  Usually you will be fine
# with default value (X-Keywords), but in case you want it
# different, here we go:
labelsheader = X-Keywords
postsynchook = notmuch new

[Repository Gmaillocalmine]
#This is the 'local' repository
type = GmailMaildir
localfolders = ~/Maildir/work2
sync_deletes = no

[Repository Gmailservermine]
type = Gmail
ssl = yes
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
remoteuser = xxxxxxxxxxxx@gmail.com

```

#### pythonfile (if any)
none

#### Logs, error

```
Folder 00order_mail2019 [acc: GmailWork]:
 Syncing 00order_mail2019: Gmail -> GmailMaildir
Folder 00order_mail2018 [acc: GmailWork]:
 ERROR: ERROR in syncfolder for GmailWork folder 00order_mail2018: Traceback (most recent call last):
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 653, in syncfolder
    remotefolder.cachemessagelist()
  File "/usr/share/offlineimap3/offlineimap/folder/Gmail.py", line 132, in cachemessagelist
    res_type, response = imapobj.fetch("'%s'" % msgsToFetch,
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 807, in fetch
    return self._simple_command(name, message_set, message_parts, **kw)
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 1684, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 1431, in _command_complete
    raise self.error('%s command error: %s %s. Data: %.100s' % (rqb.name, typ, dat, rqb.data))
imaplib2.IMAP4.error: FETCH command error: BAD [b'Could not parse command']. Data: b"MBKL15 FETCH '1:*' (FLAGS X-GM-LABELS UID)\r\n"

  FETCH command error: BAD [b'Could not parse command']. Data: b"MBKL15 FETCH '1:*' (FLAGS X-GM-LABELS UID)\r\n"
```

#### Steps to reproduce the error

- updated offlineimap3 today
- run offlineimap
- enter password for Gmail
- error is reproducible in another user in the same machine and another machine with same specs. In this case, it creates the local folders for downloading mail and then creates the error

**Comment by sudipm-mukherjee** [comment]
@dinosv Do you mean that you had been using offlineimap3 from Bullseye and only after updating to `0.0~git20210105.00d395b+dfsg-3` this problem started ?
Will it be possible to add the debug log by using `offlineimap -dALL`..

**Comment by sudipm-mukherjee** [comment]
@dinosv Can you please confirm the current offlineimap version with `dpkg -l | grep offlineimap`. And, do you know what was the previous version of offlineimap? You can find it by `cat /var/log/dpkg.log | grep offlineimap`

Will it be possible to add the debug log by using `offlineimap -dALL`

**Comment by sudipm-mukherjee** [comment]
@thekix fyi, I am able to reproduce this error. This is another problem from updating to offlineimap3 from offlineimap.

**Comment by dinosv** [comment]
> @dinosv Can you please confirm the current offlineimap version with `dpkg -l | grep offlineimap`. And, do you know what was the previous version of offlineimap? You can find it by `cat /var/log/dpkg.log | grep offlineimap`
> 
> Will it be possible to add the debug log by using `offlineimap -dALL`

Yes, sure. Thank you!

```````
cat /var/log/dpkg.log | grep offlineimap
2021-02-17 16:14:18 upgrade offlineimap:all 7.3.3+dfsg1-1 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:14:18 status half-configured offlineimap:all 7.3.3+dfsg1-1
2021-02-17 16:14:19 status unpacked offlineimap:all 7.3.3+dfsg1-1
2021-02-17 16:14:19 status half-installed offlineimap:all 7.3.3+dfsg1-1
2021-02-17 16:14:19 status unpacked offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:14:20 install offlineimap3:all <none> 0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:14:20 status half-installed offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:14:20 status unpacked offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:25:26 configure offlineimap3:all 0.0~git20210105.00d395b+dfsg-2 <none>
2021-02-17 16:25:26 status unpacked offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:25:26 status half-configured offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:25:26 status installed offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:26:08 configure offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2 <none>
2021-02-17 16:26:08 status unpacked offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:26:08 status half-configured offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 16:26:08 status installed offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:15 status installed offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:37 remove offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2 <none>
2021-02-17 22:50:37 status half-configured offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:37 status half-installed offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:38 status config-files offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:38 status not-installed offlineimap:all <none>
2021-02-17 22:50:51 status installed offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:52 remove offlineimap3:all 0.0~git20210105.00d395b+dfsg-2 <none>
2021-02-17 22:50:52 status half-configured offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:52 status half-installed offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:53 status config-files offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:50:53 status not-installed offlineimap3:all <none>
2021-02-17 22:51:12 install offlineimap3:all <none> 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:12 status half-installed offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:12 status unpacked offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:13 install offlineimap:all <none> 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:13 status half-installed offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:13 status unpacked offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:14 configure offlineimap3:all 0.0~git20210105.00d395b+dfsg-2 <none>
2021-02-17 22:51:14 status unpacked offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:14 status half-configured offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:14 status installed offlineimap3:all 0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:14 configure offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2 <none>
2021-02-17 22:51:14 status unpacked offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:14 status half-configured offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
2021-02-17 22:51:14 status installed offlineimap:all 7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2
```````

```````
dpkg -l | grep offlineimap
ii  offlineimap                                   7.3.3+dfsg1-1+0.0~git20210105.00d395b+dfsg-2      all          transitional package
ii  offlineimap3                                  0.0~git20210105.00d395b+dfsg-2                    all          IMAP/Maildir synchronization and reader support
```````
Debug is way too long to copy and paste and can not find the way to pipe it to a file :(

**Comment by sudipm-mukherjee** [comment]
@dinosv Thanks for confiming. This is indeed an upgrade from offlineimap to offlineimap3.

**Comment by sudipm-mukherjee** [comment]
So, the easiest way to reproduce this is to use `synclabels = yes` in offlineimaprc file and try to sync a folder which has `_` in it.
I created a label `abcd_1234` in my gmail and then `offlineimap -o -f abcd_1234` to get the error.

@dinosv I will suggest commenting `synclabels` for now until @thekix finds a fix.

**Comment by sudipm-mukherjee** [comment]
@dinosv Can you please test with the following patch and check if it fixes the problem on both the machines.
```
diff --git a/offlineimap/folder/Gmail.py b/offlineimap/folder/Gmail.py
index af236e1..8d64ac4 100644
--- a/offlineimap/folder/Gmail.py
+++ b/offlineimap/folder/Gmail.py
@@ -125,11 +125,10 @@ class GmailFolder(IMAPFolder):
             if not msgsToFetch:
                 return  # No messages to sync
 
-            # Get the flags and UIDs for these. single-quotes prevent
-            # imaplib2 from quoting the sequence.
+            # Get the flags and UIDs for these.
             #
             # NB: msgsToFetch are sequential numbers, not UID's
-            res_type, response = imapobj.fetch("'%s'" % msgsToFetch,
+            res_type, response = imapobj.fetch("%s" % msgsToFetch,
                                                '(FLAGS X-GM-LABELS UID)')
             if res_type != 'OK':
                 raise OfflineImapError(
@@ -147,6 +146,9 @@ class GmailFolder(IMAPFolder):
             # Discard initial message number.
             if messagestr is None:
                 continue
+            # We need a str messagestr
+            if isinstance(messagestr, bytes):
+                messagestr = messagestr.decode(encoding='utf-8')
             messagestr = messagestr.split(' ', 1)[1]
             # e.g.: {'X-GM-LABELS': '("Webserver (RW.net)" "\\Inbox" GInbox)', 'FLAGS': '(\\Seen)', 'UID': '275440'}
             options = imaputil.flags2hash(messagestr)
@@ -164,6 +166,8 @@ class GmailFolder(IMAPFolder):
                 else:
                     labels = set()
                 labels = labels - self.ignorelabels
+                if isinstance(messagestr, str):
+                    messagestr = bytes(messagestr, 'utf-8')
                 rtime = imaplibutil.Internaldate2epoch(messagestr)
                 self.messagelist[uid] = {'uid': uid, 'flags': flags, 'labels': labels, 'time': rtime}
```
@thekix fyi.

**Comment by dinosv** [comment]
> @dinosv Can you please test with the following patch and check if it fixes the problem on both the machines.
> @thekix fyi.

Thank you very much @sudipm-mukherjee ! it works good in both machines. Now I am downloading about five hundred new emails...

**Comment by sudipm-mukherjee** [comment]
Thanks for testing @dinosv.
And can you please reopen this issue, it will be automatically closed when the patch is merged by @thekix after he has tested. I will raise a PR.

**Comment by dinosv** [comment]
Sure

**Comment by rsekman** [comment]
This bug happened to me on 8.0.0. The cause turned out to be that my `.offlineimaprc` contained 
```py
idlefolders = ['[Gmail].All Mail']
```
Deleting this line resolved the issue.
