### ISSUE TITLE
How to install imaplib2?

### ISSUE THREAD

**Issue by xianwenchen** [OfflineIMAP/offlineimap3#69]
#### General informations

- system/distribution (with version): Void 
- offlineimap version (`offlineimap -V`): git master
- Python version: 3.9
- server name or domain: NA
- CLI options: `python3 offlineimap.py`

#### Configuration file offlineimaprc

```
NA
```

#### Logs, error

```
Traceback (most recent call last):
  File "/home/c/data/programming/python/offlineimap3/offlineimap.py", line 19, in <module>
    from offlineimap import OfflineImap
  File "/home/c/data/programming/python/offlineimap3/offlineimap/__init__.py", line 20, in <module>
    from offlineimap.init import OfflineImap
  File "/home/c/data/programming/python/offlineimap3/offlineimap/init.py", line 34, in <module>
    from offlineimap import threadutil, accounts, folder, mbnames
  File "/home/c/data/programming/python/offlineimap3/offlineimap/accounts.py", line 26, in <module>
    from offlineimap.repository import Repository
  File "/home/c/data/programming/python/offlineimap3/offlineimap/repository/__init__.py", line 20, in <module>
    from offlineimap.repository.IMAP import IMAPRepository, MappedIMAPRepository
  File "/home/c/data/programming/python/offlineimap3/offlineimap/repository/IMAP.py", line 25, in <module>
    from offlineimap import folder, imaputil, imapserver, OfflineImapError
  File "/home/c/data/programming/python/offlineimap3/offlineimap/folder/__init__.py", line 4, in <module>
    from . import Base, Gmail, IMAP, Maildir, LocalStatus, UIDMaps
  File "/home/c/data/programming/python/offlineimap3/offlineimap/folder/Gmail.py", line 22, in <module>
    from offlineimap import imaputil, imaplibutil, OfflineImapError
  File "/home/c/data/programming/python/offlineimap3/offlineimap/imaplibutil.py", line 30, in <module>
    from imaplib2 import IMAP4, IMAP4_SSL, InternalDate
ImportError: cannot import name 'IMAP4' from 'imaplib2' (/home/c/.local/lib/python3.9/site-packages/imaplib2/__init__.py)
```

#### Steps to reproduce the error

- I installed imaplib2 using pip `pip install --user imaplib2`
- offlineimap3 compalined that could not import name IMAP4 from imaplib2.

**Comment by xianwenchen** [comment]
Thank you!
